"""Behaviour tests: does the finished agent actually play better?

PROVIDED INFRASTRUCTURE. Do not edit this file.

The contract tests check that your agent is built the right way. These
check that it works. They play full episodes, so they take a few seconds.

Run them with:

    python -m unittest tests.test_chapter2_performance -v
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.headless import run_trials, summarize  # noqa: E402
from pacman.registry import resolve_agents  # noqa: E402

SEEDS = list(range(1, 13))


class TestAgentBehaviour(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.agents = resolve_agents(
            ["student", "simple_reflex"], PROJECT_ROOT / "agent.py"
        )
        cls.rows = run_trials(cls.agents, SEEDS, difficulty="normal")
        cls.summary = {row["agent"]: row for row in summarize(cls.rows)}

    def test_agent_finishes_every_episode_without_error(self):
        student_rows = [row for row in self.rows if row["agent"] == "student"]
        self.assertEqual(len(student_rows), len(SEEDS))

    def test_agent_wins_most_episodes(self):
        win_rate = self.summary["student"]["win_rate"]
        self.assertGreaterEqual(
            win_rate,
            0.60,
            f"Your agent cleared the maze in {win_rate:.0%} of episodes. A "
            "finished Chapter 2 agent should win most of them on 'normal'. "
            "Check your ghost weights and your food-distance term.",
        )

    def test_agent_beats_the_simple_reflex_baseline(self):
        student = self.summary["student"]["mean_performance"]
        reflex = self.summary["simple_reflex"]["mean_performance"]
        self.assertGreater(
            student,
            reflex,
            f"Mean performance {student} did not beat the simple reflex "
            f"baseline at {reflex}. Adding internal state and a utility "
            "function is supposed to help.",
        )

    def test_memory_reduces_pointless_reversals(self):
        student = self.summary["student"]["mean_backtracks"]
        reflex = self.summary["simple_reflex"]["mean_backtracks"]
        self.assertLessEqual(
            student,
            reflex,
            f"Your agent reversed into its previous tile {student} times per "
            f"episode on average, versus {reflex} for the memoryless "
            "baseline. That is what the backtrack penalty is for.",
        )


if __name__ == "__main__":
    unittest.main()
