"""Contract tests for the Chapter 2 agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Read these tests. They are the specification. Each test name starts with
the TODO item it checks, so a failure tells you exactly which part of
``agent.py`` to go work on.

Run them with:

    python -m unittest discover -s tests -v
"""

from __future__ import annotations

import dataclasses
import inspect
import re
import sys
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

AGENT_PATH = PROJECT_ROOT / "agent.py"

# A tiny open room. Pac-Man starts at (2, 2) with room to move in every
# direction, which keeps these tests independent of the real maze.
TEST_LEVEL = (
    "#####",
    "#...#",
    "#.P.#",
    "#...#",
    "#####",
)


def load_agent_module():
    import importlib.util

    spec = importlib.util.spec_from_file_location("student_agent_under_test", AGENT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["student_agent_under_test"] = module
    spec.loader.exec_module(module)
    return module


class Chapter2Base(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_agent_module()
        cls.maze = MazeModel(TEST_LEVEL)

    def new_agent(self):
        return self.module.PacManAgent(self.maze)

    def make_percept(self, agent, **overrides):
        """Build a percept containing whatever fields the student declared."""
        defaults = {
            "player": (2, 2),
            "current_direction": DIRECTIONS["RIGHT"],
            "pellets": frozenset({(2, 3), (1, 1)}),
            "power_pellets": frozenset(),
            "ghosts": tuple(),
            "released_ghosts": tuple(),
            "legal_actions": (
                DIRECTIONS["LEFT"],
                DIRECTIONS["RIGHT"],
                DIRECTIONS["UP"],
                DIRECTIONS["DOWN"],
            ),
            "frightened_time_remaining": 0.0,
        }
        defaults.update(overrides)
        declared = [f.name for f in dataclasses.fields(agent.percept_class)]
        return agent.percept_class(**{name: defaults[name] for name in declared})


class TestCH2_1_Percept(Chapter2Base):
    def test_ch2_1_percept_declares_every_required_sensor_field(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        required = {
            "player",
            "current_direction",
            "pellets",
            "power_pellets",
            "released_ghosts",
            "legal_actions",
            "frightened_time_remaining",
        }
        missing = required - declared
        self.assertFalse(
            missing,
            f"CH2-1: Percept is missing {sorted(missing)}. Add these fields.",
        )

    def test_ch2_1_percept_fields_are_all_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(
            unknown,
            f"CH2-1: Percept declares {sorted(unknown)}, which this environment "
            f"cannot sense. Valid names: {list(Simulation.SENSOR_FIELDS)}",
        )

    def test_ch2_1_agent_exposes_its_percept_class(self):
        self.assertIs(
            self.new_agent().percept_class,
            self.module.Percept,
            "CH2-1: PacManAgent.percept_class must refer to your Percept.",
        )


class TestCH2_2_NamedWeights(Chapter2Base):
    def test_ch2_2_weights_cover_ghosts_and_memory(self):
        names = {f.name for f in dataclasses.fields(self.module.UtilityWeights)}
        self.assertGreaterEqual(
            len(names),
            10,
            f"CH2-2: only {len(names)} named weights. Every number that "
            "expresses a preference belongs in UtilityWeights.",
        )
        joined = " ".join(names).lower()
        for topic in ("ghost", "revisit", "backtrack"):
            self.assertIn(
                topic,
                joined,
                f"CH2-2: no weight mentions '{topic}'. Name the preferences "
                "for ghost danger, revisiting, and reversing.",
            )

    def test_ch2_2_weights_are_actually_used(self):
        """Flipping the collision weight must change what the agent does."""
        ghost_tile = (2, 3)
        right = DIRECTIONS["RIGHT"]

        cautious = self.new_agent()
        percept = self.make_percept(
            cautious, released_ghosts=(ghost_tile,), pellets=frozenset({(2, 3)})
        )
        cautious_action = cautious.choose_action(percept)
        self.assertNotEqual(
            cautious_action,
            right,
            "CH2-2/CH2-5: the agent walked straight onto a dangerous ghost.",
        )

        reckless = self.new_agent()
        collision_field = next(
            (
                f.name
                for f in dataclasses.fields(self.module.UtilityWeights)
                if "collision" in f.name or "caught" in f.name
            ),
            None,
        )
        self.assertIsNotNone(
            collision_field,
            "CH2-2: expected a weight named for the collision or caught case.",
        )
        reckless.weights = dataclasses.replace(
            reckless.weights, **{collision_field: 5000.0}
        )
        reckless_percept = self.make_percept(
            reckless, released_ghosts=(ghost_tile,), pellets=frozenset({(2, 3)})
        )
        self.assertEqual(
            reckless.choose_action(reckless_percept),
            right,
            "CH2-2: changing the collision weight had no effect, so the named "
            "weights are not the numbers actually driving the decision.",
        )


class TestCH2_3_and_4_InternalState(Chapter2Base):
    def test_ch2_3_internal_state_exists(self):
        agent = self.new_agent()
        self.assertTrue(
            hasattr(agent, "visit_counts"), "CH2-3: no visit_counts attribute."
        )
        self.assertTrue(
            hasattr(agent, "position_history"),
            "CH2-3: no position_history attribute.",
        )

    def test_ch2_4_update_internal_state_records_the_percept(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        agent.update_internal_state(percept)
        self.assertEqual(
            agent.visit_counts.get((2, 2)),
            1,
            "CH2-4: visiting a tile must increment its visit count.",
        )
        agent.update_internal_state(percept)
        self.assertEqual(
            agent.visit_counts.get((2, 2)),
            2,
            "CH2-4: repeat visits must keep counting.",
        )
        self.assertIn(
            (2, 2),
            list(agent.position_history),
            "CH2-4: position_history must record where the agent has been.",
        )

    def test_ch2_4_position_history_is_bounded(self):
        agent = self.new_agent()
        for _ in range(50):
            agent.update_internal_state(self.make_percept(agent))
        self.assertLessEqual(
            len(agent.position_history),
            8,
            "CH2-4: position_history should be a short rolling window, not an "
            "unbounded log. Use collections.deque(maxlen=4).",
        )


class TestCH2_5_EvaluateAction(Chapter2Base):
    REQUIRED_KEYS = (
        "food_distance",
        "regular_pellet",
        "power_pellet",
        "ghost",
        "continuation",
        "revisit",
        "backtrack",
        "food_distance_steps",
        "ghost_distance_steps",
        "revisit_count",
    )

    def test_ch2_5_returns_utility_and_named_contributions(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        result = agent.evaluate_action(percept, DIRECTIONS["RIGHT"])
        self.assertIsInstance(result, tuple, "CH2-5: return a (utility, dict) tuple.")
        self.assertEqual(len(result), 2, "CH2-5: return exactly two values.")

        utility, contributions = result
        self.assertIsInstance(utility, float, "CH2-5: utility must be a float.")
        self.assertIsInstance(contributions, dict, "CH2-5: contributions must be a dict.")

        missing = [key for key in self.REQUIRED_KEYS if key not in contributions]
        self.assertFalse(missing, f"CH2-5: contributions is missing {missing}.")

    def test_ch2_5_weighted_terms_sum_to_the_total(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        utility, contributions = agent.evaluate_action(percept, DIRECTIONS["RIGHT"])
        weighted = (
            "food_distance",
            "regular_pellet",
            "power_pellet",
            "ghost",
            "continuation",
            "revisit",
            "backtrack",
        )
        self.assertAlmostEqual(
            utility,
            sum(contributions[key] for key in weighted),
            places=6,
            msg="CH2-5: the weighted contributions must add up to the total.",
        )

    def test_ch2_5_illegal_action_raises(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent, legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["LEFT"])
        )
        with self.assertRaises(
            ValueError, msg="CH2-5: evaluating an illegal action must raise ValueError."
        ):
            agent.evaluate_action(percept, DIRECTIONS["UP"])

    def test_ch2_5_nearby_ghost_lowers_utility(self):
        agent = self.new_agent()
        right = DIRECTIONS["RIGHT"]
        safe, _ = agent.evaluate_action(self.make_percept(agent), right)
        risky, _ = agent.evaluate_action(
            self.make_percept(agent, released_ghosts=((2, 3),)), right
        )
        self.assertLess(
            risky, safe, "CH2-5: a ghost on the landing tile must reduce utility."
        )

    def test_ch2_5_frightened_ghost_raises_utility(self):
        agent = self.new_agent()
        right = DIRECTIONS["RIGHT"]
        dangerous, _ = agent.evaluate_action(
            self.make_percept(agent, released_ghosts=((2, 3),)), right
        )
        edible, _ = agent.evaluate_action(
            self.make_percept(
                agent,
                released_ghosts=((2, 3),),
                frightened_time_remaining=5.0,
            ),
            right,
        )
        self.assertGreater(
            edible,
            dangerous,
            "CH2-5: during frightened mode a ghost is prey, not a hazard.",
        )

    def test_ch2_5_memory_lowers_the_utility_of_a_stale_tile(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        right = DIRECTIONS["RIGHT"]

        fresh_utility, fresh = agent.evaluate_action(percept, right)
        agent.visit_counts[(2, 3)] = 5
        stale_utility, stale = agent.evaluate_action(percept, right)

        self.assertLess(
            stale_utility,
            fresh_utility,
            "CH2-5: a tile visited five times must score below an unvisited one.",
        )
        self.assertLess(
            stale["revisit"],
            fresh["revisit"],
            "CH2-5: the revisit contribution must carry that penalty.",
        )


class TestCH2_6_and_7_Selection(Chapter2Base):
    def test_ch2_6_no_legal_action_is_handled(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, legal_actions=tuple())
        self.assertEqual(
            agent.choose_action(percept),
            (0, 0),
            "CH2-6: with no legal actions, return (0, 0).",
        )
        self.assertIn(
            "No legal",
            agent.last_reason,
            "CH2-6: say so in last_reason when there is no legal move.",
        )

    def test_ch2_6_returned_action_is_always_legal(self):
        agent = self.new_agent()
        for legal in [
            (DIRECTIONS["LEFT"],),
            (DIRECTIONS["UP"], DIRECTIONS["DOWN"]),
            tuple(DIRECTIONS.values()),
        ]:
            percept = self.make_percept(agent, legal_actions=legal)
            self.assertIn(
                agent.choose_action(percept),
                legal,
                "CH2-6: choose_action returned an action that was not legal.",
            )

    def test_ch2_6_choose_action_updates_memory_once_per_turn(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        agent.choose_action(percept)
        self.assertEqual(
            agent.visit_counts.get((2, 2)),
            1,
            "CH2-6: choose_action must call update_internal_state exactly once.",
        )
        agent.choose_action(percept)
        self.assertEqual(
            agent.visit_counts.get((2, 2)),
            2,
            "CH2-6: choose_action must call update_internal_state exactly once.",
        )

    def test_ch2_6_selection_uses_evaluate_action(self):
        """Rigging the scorer must fully determine the choice."""
        agent = self.new_agent()
        target = DIRECTIONS["DOWN"]

        def fake_evaluate(percept, action):
            score = 100.0 if action == target else -100.0
            return score, {
                "food_distance": 0.0,
                "regular_pellet": 0.0,
                "power_pellet": 0.0,
                "ghost": 0.0,
                "continuation": 0.0,
                "revisit": 0.0,
                "backtrack": 0.0,
                "food_distance_steps": 0.0,
                "ghost_distance_steps": 0.0,
                "revisit_count": 0.0,
            }

        agent.evaluate_action = fake_evaluate
        self.assertEqual(
            agent.choose_action(self.make_percept(agent)),
            target,
            "CH2-6: choose_action must pick the action evaluate_action scores "
            "highest, not recompute its own score inline.",
        )

    def test_ch2_7_last_reason_reports_the_evidence(self):
        agent = self.new_agent()
        agent.choose_action(self.make_percept(agent))
        for token in ("U=", "food=", "ghost=", "memory="):
            self.assertIn(
                token,
                agent.last_reason,
                f"CH2-7: last_reason must contain {token!r}. Current value: "
                f"{agent.last_reason!r}",
            )
        self.assertLessEqual(
            len(agent.last_reason),
            120,
            "CH2-7: keep last_reason to one short line; it is drawn on screen.",
        )


class TestScopeAndIntegrity(Chapter2Base):
    def test_scope_agent_only_needs_the_static_maze(self):
        agent = self.module.PacManAgent(self.maze)
        self.assertIsNotNone(agent)

    def test_scope_no_environment_access(self):
        source = AGENT_PATH.read_text(encoding="utf-8")
        for forbidden in (
            "pacman.rules",
            "pacman.render",
            "pacman.entities",
            "pacman.headless",
            "Simulation",
        ):
            self.assertNotIn(
                forbidden,
                source,
                f"agent.py references {forbidden!r}. The agent may only use its "
                "percept and the static MazeModel.",
            )

    def test_scope_no_search_implementation(self):
        source = AGENT_PATH.read_text(encoding="utf-8")
        for forbidden in ("import heapq", "PriorityQueue", "def a_star", "def astar"):
            self.assertNotIn(
                forbidden,
                source,
                f"agent.py contains {forbidden!r}. Search algorithms are "
                "Chapter 3. Use self.maze.distance instead.",
            )

    def test_scope_todo_markers_removed(self):
        source = inspect.getsource(self.module.PacManAgent)
        self.assertFalse(
            "starter policy" in source,
            "The starter policy is still in choose_action. Replace it with a "
            "call to update_internal_state followed by evaluate_action.",
        )
        remaining = sorted(
            set(re.findall(r"TODO\(CH2-\d+\)", AGENT_PATH.read_text(encoding="utf-8")))
        )
        self.assertFalse(
            remaining,
            f"Unfinished TODO markers still in agent.py: {remaining}. Delete "
            "each marker once you have completed that item.",
        )


if __name__ == "__main__":
    unittest.main()
