#!/usr/bin/env python3
"""Watch an agent play in a window.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Examples:
    python tools/play.py                          # your agent, seed 0
    python tools/play.py --seed 7                 # a different ghost pattern
    python tools/play.py --agent simple_reflex    # the provided baseline
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.maze import MazeModel           # noqa: E402
from pacman.rules import DIFFICULTIES        # noqa: E402
from pacman.registry import resolve_agents  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the Pac-Man agent demo.")
    parser.add_argument(
        "--agent",
        default="student",
        help="student, simple_reflex, or random (default: student)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="ghost randomness seed; the same seed always replays identically",
    )
    parser.add_argument(
        "--difficulty",
        default="normal",
        choices=sorted(DIFFICULTIES),
        help="normal is what you are graded on; on hard the ghosts move faster than you",
    )
    parser.add_argument(
        "--agent-file",
        type=Path,
        default=PROJECT_ROOT / "agent.py",
        help="path to the student agent file",
    )
    args = parser.parse_args()

    try:
        agents = resolve_agents([args.agent], args.agent_file)
    except (ValueError, FileNotFoundError, AttributeError) as error:
        parser.error(str(error))

    try:
        from pacman.render import Window
    except ImportError:
        print(
            "Pygame is not installed. Install it with:\n"
            "    python -m pip install -r requirements.txt\n"
            "You can still run tools/run_trials.py without it.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    difficulty = DIFFICULTIES[args.difficulty]
    Window(
        agent_factory=agents[args.agent],
        agent_label=args.agent,
        seed=args.seed,
        maze=MazeModel(difficulty.level),
        difficulty=difficulty,
    ).run()


if __name__ == "__main__":
    main()
