#!/usr/bin/env python3
"""Compare agents over a shared set of seeds. No window, no Pygame needed.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Example:
    python tools/run_trials.py --agents student,simple_reflex,random --count 30
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.headless import (   # noqa: E402
    SUMMARY_COLUMNS,
    TRIAL_COLUMNS,
    format_summary_table,
    run_trials,
    summarize,
    write_csv,
)
from pacman.rules import DIFFICULTIES        # noqa: E402
from pacman.registry import resolve_agents  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description="Paired-seed agent comparison.")
    parser.add_argument(
        "--agents",
        default="student,simple_reflex,random",
        help="comma-separated agent names (default: student,simple_reflex,random)",
    )
    parser.add_argument("--count", type=int, default=30, help="number of seeds")
    parser.add_argument(
        "--difficulty",
        default="normal",
        choices=sorted(DIFFICULTIES),
        help="normal is what you are graded on; on hard the ghosts move faster than you",
    )
    parser.add_argument("--seed-start", type=int, default=1)
    parser.add_argument("--max-decisions", type=int, default=1500)
    parser.add_argument("--max-time-ms", type=int, default=240_000)
    parser.add_argument(
        "--agent-file", type=Path, default=PROJECT_ROOT / "agent.py"
    )
    parser.add_argument(
        "--output", type=Path, default=PROJECT_ROOT / "results" / "trials.csv"
    )
    parser.add_argument(
        "--summary", type=Path, default=PROJECT_ROOT / "results" / "summary.csv"
    )
    args = parser.parse_args()

    try:
        agents = resolve_agents(args.agents.split(","), args.agent_file)
    except (ValueError, FileNotFoundError, AttributeError) as error:
        parser.error(str(error))

    if not agents:
        parser.error("No agents selected.")

    seeds = list(range(args.seed_start, args.seed_start + args.count))

    try:
        rows = run_trials(
            agents,
            seeds,
            difficulty=args.difficulty,
            max_decisions=args.max_decisions,
            max_time_ms=args.max_time_ms,
        )
    except NotImplementedError as error:
        print(
            f"Your agent raised NotImplementedError: {error}\n"
            "Finish the TODO(CH2-...) items in agent.py, then rerun.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    summaries = summarize(rows)
    write_csv(args.output, rows, TRIAL_COLUMNS)
    write_csv(args.summary, summaries, SUMMARY_COLUMNS)

    print(format_summary_table(summaries))
    print()
    print(f"per-trial rows -> {args.output}")
    print(f"summary rows   -> {args.summary}")


if __name__ == "__main__":
    main()
