"""Look up an agent by name.

PROVIDED INFRASTRUCTURE. Do not edit this file.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Callable

from .agents import RandomAgent, SimpleReflexAgent
from .maze import MazeModel

AgentFactory = Callable[[MazeModel], Any]

BUILTIN_AGENTS: dict[str, AgentFactory] = {
    "random": lambda maze: RandomAgent(maze),
    "simple_reflex": lambda maze: SimpleReflexAgent(maze),
}


def load_student_agent(path: Path | str = "agent.py") -> AgentFactory:
    """Import a student ``agent.py`` and return a factory for its agent."""
    path = Path(path).resolve()
    if not path.exists():
        raise FileNotFoundError(f"No agent file at {path}")

    project_root = path.parent
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    spec = importlib.util.spec_from_file_location("student_agent", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules["student_agent"] = module
    spec.loader.exec_module(module)

    if not hasattr(module, "PacManAgent"):
        raise AttributeError(f"{path} does not define PacManAgent")

    return lambda maze: module.PacManAgent(maze)


def resolve_agents(
    names: list[str],
    student_path: Path | str = "agent.py",
) -> dict[str, AgentFactory]:
    """Turn a list of agent names into name -> factory."""
    agents: dict[str, AgentFactory] = {}
    for name in names:
        key = name.strip()
        if not key:
            continue
        if key in BUILTIN_AGENTS:
            agents[key] = BUILTIN_AGENTS[key]
        elif key == "student":
            agents[key] = load_student_agent(student_path)
        else:
            known = ", ".join(sorted(set(BUILTIN_AGENTS) | {"student"}))
            raise ValueError(f"Unknown agent {key!r}. Choose from: {known}")
    return agents
