"""Simple reflex agent (AIMA 4e Figure 2.10).

PROVIDED INFRASTRUCTURE. Do not edit this file.

The whole agent is a short list of condition-action rules applied to the
CURRENT percept. There is no internal state, so it cannot know it has
already eaten this corridor, and it cannot tell a dead end from a through
route. Watch it in the window: it clears the easy pellets quickly, then
paces back and forth because every percept in an empty corridor looks the
same to it.

That failure is the whole reason Chapter 2 goes on to describe model-based
agents, and it is what your agent in ``agent.py`` is meant to fix.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..maze import DIRECTION_NAMES, MazeModel


@dataclass(frozen=True)
class ReflexPercept:
    player: tuple[int, int]
    current_direction: tuple[int, int]
    pellets: frozenset[tuple[int, int]]
    power_pellets: frozenset[tuple[int, int]]
    released_ghosts: tuple[tuple[int, int], ...]
    legal_actions: tuple[tuple[int, int], ...]
    frightened_time_remaining: float


class SimpleReflexAgent:
    percept_class = ReflexPercept

    def __init__(self, maze: MazeModel):
        self.maze = maze
        self.last_reason = "Waiting for first percept."

    def choose_action(self, percept: ReflexPercept) -> tuple[int, int]:
        if not percept.legal_actions:
            self.last_reason = "No legal move."
            return (0, 0)

        frightened = percept.frightened_time_remaining > 0.0
        ghosts = set(percept.released_ghosts)
        landing = {
            action: self.maze.step(percept.player, action)
            for action in percept.legal_actions
        }

        # Rule 1: never walk onto a dangerous ghost.
        safe = [
            action
            for action, tile in landing.items()
            if frightened or tile not in ghosts
        ]
        if not safe:
            safe = list(percept.legal_actions)
            rule = "cornered"
        else:
            rule = "safe"

        # Rule 2: eat a frightened ghost that is right next to you.
        if frightened:
            for action in safe:
                if landing[action] in ghosts:
                    return self._commit(action, "eat frightened ghost")

        # Rule 3: step onto an adjacent power pellet, then an adjacent pellet.
        for action in safe:
            if landing[action] in percept.power_pellets:
                return self._commit(action, "adjacent power pellet")
        for action in safe:
            if landing[action] in percept.pellets:
                return self._commit(action, "adjacent pellet")

        # Rule 4: otherwise keep going straight if you can.
        if percept.current_direction in safe:
            return self._commit(percept.current_direction, f"continue ({rule})")

        # Rule 5: otherwise take the first legal action.
        return self._commit(safe[0], f"default ({rule})")

    def _commit(self, action: tuple[int, int], rule: str) -> tuple[int, int]:
        self.last_reason = f"{DIRECTION_NAMES[action]} | rule: {rule}"
        return action
